{
 "title": "NUT",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Battery Temperature",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    { "expr": "nut_battery_temperature" }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    { "expr": "nut_battery_charge" }
   ]
  },
  {
   "title": "Ups Load",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    { "expr": "nut_ups_load" }
   ]
  },
  {
   "title": "Battery Runtime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    { "expr": "nut_battery_runtime" }
   ]
  },
  {
   "title": "Ups Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "nut_ups_status" }
   ]
  },
  {
   "title": "Battery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Battery Charge",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      { "expr": "nut_battery_charge", "legendFormat": "Battery Charge" }
     ]
    },
    {
     "title": "Battery Runtime",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      { "expr": "nut_battery_runtime", "legendFormat": "Battery runtime" },
      {
       "expr": "nut_battery_runtime_low",
       "legendFormat": "Remaining battery runtime when UPS switches to LB"
      }
     ]
    },
    {
     "title": "Battery Voltage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "volt" }
     ],
     "targets": [
      { "expr": "nut_battery_voltage", "legendFormat": "Battery voltage (V)" },
      { "expr": "nut_battery_voltage_nominal", "legendFormat": "Nominal battery voltage (V)" }
     ]
    },
    {
     "title": "Battery Temperature ",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      { "expr": "nut_battery_temperature", "legendFormat": "Battery Temperature (C)" }
     ]
    }
   ]
  },
  {
   "title": "Input",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Input Voltage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "volt" }
     ],
     "targets": [
      { "expr": "nut_input_voltage", "legendFormat": "High voltage (V)" }
     ]
    },
    {
     "title": "Input Voltage Transfer",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "volt" }
     ],
     "targets": [
      { "expr": "nut_input_transfer_low", "legendFormat": "Low voltage transfer point (V)" },
      {
       "expr": "nut_input_transfer_high",
       "legendFormat": "High voltage transfer point (V)"
      }
     ]
    }
   ]
  },
  {
   "title": "Output",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Output current (A)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "amp" }
     ],
     "targets": [
      { "expr": "nut_output_current", "legendFormat": "Output current (A)" }
     ]
    },
    {
     "title": "Output Voltage (V)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "volt" }
     ],
     "targets": [
      { "expr": "nut_output_voltage", "legendFormat": "Output voltage (V)" },
      { "expr": "nut_output_voltage_nominal", "legendFormat": "Nominal output voltage (V)" }
     ]
    },
    {
     "title": "Output Hertz (V)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "hertz" }
     ],
     "targets": [
      { "expr": "nut_output_frequency", "legendFormat": "Output frequency (Hz)" }
     ]
    }
   ]
  }
 ]
}